---
user: nesi-apps-admin
licence_conf: "./licences.yml"
fail_tolerance: 3
resources:
  mahuika:
    pattern: mahuika(?=\d{2})|(wbn|wbg|vgpuwbg|wbl|wch|wbh|wcl)(?=\d{3})
  maui:
    pattern: maui(?=\d{2})|nid(?=\d{5})
  maui_ancil:
    pattern: wsn\d{3}|vgpuwsg\d{3}
  other:
    pattern: nesi\S?|niwa\S?

# Currently unused.
fix_slurm_share: true
fix_slurm_count: true
check_user: true
loglevel: info
validate: true
soak: true
squeue_poll_period: 60
path_modulelist: "../module_tracker/module_list.json"
